import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Button, Grid } from '@mui/material'
import { useEffect, useRef, useState } from 'react'
import { fabric } from 'fabric'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [canvas, setCanvas] = useState(null)

  useEffect(() => {
    setCanvas(new fabric.Canvas('canvas'))
  }, [])

  const handleImageSelect = async(e) => {
    if (canvas) {
      const ctx = canvas.getContext('2d')
      let img = new Image()
      img.src = URL.createObjectURL(e.target.files[0])
      img.onload = () => {
       canvas.setWidth(img.width)
       canvas.setHeight(img.height)
       canvas.renderAll()
        ctx.drawImage(img, 0, 0)
      }
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid>
          <Button component="label" variant="contained">
            Upload Button
            <input hidden type="file" onChange={handleImageSelect} />
          </Button>
        </Grid>
        <div>
          <canvas id="canvas" />
        </div>
      </main>
    </>
  )
}
